---
postfix_hostname: "{{ansible_hostname}}"
postfix_networks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"

## Relay server
## Empty for direct delivery to Internet
# postfix_relay_server: "[mail.isp.tld]"
postfix_relay_server: "[smtp.mailgun.org]:587"
postfix_inet_interfaces: loopback-only
postfix_inet_protocols: all
postfix_mydestination: "{{postfix_hostname}}, localhost"
postfix_relay_domains: "{{postfix_mydestination}}, example.com"

## List of password for relay
# postfix_sasl_passwd:
#	- mail.my-isp.org      test:testpass
postfix_sasl_passwd:
  - smtp.mailgun.org  postmaster@stojg.se:password
## List of TLS policies
# postfix_tls_policy:
#	- mail.my-isp.org      encrypt
postfix_tls_policy:
  - smtp_tls_security_level = may
  - smtpd_tls_security_level = may
  - smtp_tls_note_starttls_offer = yes

postfix_conf_dir: /etc/postfix
