# all groups will use these

common_packages:
  - ntp
  - mosh
  - htop
  - vim
  - sudo
  - curl
  - wget
  - git-core
  - mailutils
  - python-pip
  - python-pycurl
  - python-yaml
  - debian-keyring
  - debian-archive-keyring
  - sysstat
  - unzip

postfix_relay_server: "[smtp.mailgun.org]:587"

newrelic_license_key: "1234567890123456789012345678901234567890"


consul_node_role: "bootstrap"
consul_iface: "eth0"
