---
# File: tasks/Debian.yml - Debian tasks for Consul

- name: "Distribution specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: OS Packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: consul_debian_os_packages
  tags: installation

- name: Download Consul
  get_url: "url={{ consul_zip_url }} dest=/tmp/{{ consul_debian_pkg }} sha256sum={{ consul_debian_sha256 }} timeout=74"
  tags: installation

- name: Install Consul
  unarchive: "copy=no src=/tmp/{{ consul_debian_pkg }} dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=755"
  tags: installation

- name: Cleanup
  file: path="/tmp/{{ consul_debian_pkg }}" state=absent
  tags: installation
